// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0
// source: query.sql

package db_sqlc

import (
	"context"
)

const addTodo = `-- name: AddTodo :exec
INSERT INTO todo (uuid, value)
    VALUES (?, ?)
`

type AddTodoParams struct {
	Uuid  string
	Value string
}

func (q *Queries) AddTodo(ctx context.Context, arg AddTodoParams) error {
	_, err := q.db.ExecContext(ctx, addTodo, arg.Uuid, arg.Value)
	return err
}
